### PR TITLE
Extend time and chrono skips by another 6 months.

### PR DESCRIPTION
**Pull request by vext01**
```
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!

Crate:         time
Version:       0.1.44
Title:         Potential segfault in the time crate
Date:          2020-11-18
ID:            RUSTSEC-2020-0071
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:      Upgrade to >=0.2.23
Dependency tree:
```

### CODE REVIEW

**Comment by vext01** [comment]
This needs a docker config. On it.

**Comment by vext01** [comment]
[af10875](https://github.com/softdevteam/sd_audit/pull/19/commits/af10875675934fe42dd8efcbe234051a34d7b413) makes CI work.

Tested manually with docker.

**Comment by ltratt** [comment]
Squash or merge as-is?

**Comment by vext01** [comment]
as-is, as the CI stuff is unrelated.

**Pull request merged**
